name: deploy

on: 
  pull_request:
    #types: [closed]
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Update Server Repo
      uses: maddox/actions/ssh@master
      env:
        PRIVATE_KEY: ${{ secrets.APOLLO_KEY }}
        HOST: 35.188.203.73
        USER: ${{ secrets.APOLLO_USER }}
      with:
        args: |
          cd apollo
          git pull