name: deploy

on: 
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Update Server Repo
      uses: maddox/actions/ssh@master
      env:
        PRIVATE_KEY: ${{ secrets.APOLLO_KEY }}
        HOST: ${{ secrets.APOLLO_HOST }}
        USER: ${{ secrets.APOLLO_USER }}
      with:
        args: |
          cd sandbox
          git pull