name: deploy

on: 
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Update code on server
      uses: maddox/actions/ssh@master
      with:
        args: |
          cd apollo && git pull
          secrets: [${{ secrets.APOLLO_KEY}}, ${{ secrets.APOLLO_HOST}},${{ secrets.APOLLO_USER}}]